@baseUrl=http://localhost:4001

POST http://localhost:4001/user/signup
Content-Type: application/json

{
  "name": "abc",
  "email": "abc@gmail.com",
  "password":"abc1234",
  "referCode": "ABC",
  "parentCode":"MANTT",
  "role":"Admin"
}

###

GET http://localhost:4001/user/all

###
POST http://localhost:4001/user/id
Content-Type: application/json

{
  "_id":"650d5775433c009f6b743885"
}

###
POST http://localhost:4001/user/set
Content-Type: application/json

{
  "_id":"650d515c06881e533d9652f0",
  "parentCode":"ABCD"
}